const messageCreate = require("../../eventos/guild/messageCreate");

let listaPiedra = {
    "rria" : "quepaja",
    "FEO" : "usted",
    "algo" : "define algo porque puedo decir muchas cosas y QUESESO",
    "dash" : "tablero de geometria",
    "arbol" : "talable",
    "besto" : "besto que",
    "RPG" : "nambre mejor pongan juegos de carrera",
    "rated" : "pasen nivel con rated para tenerlo en mi cuenta",
    "waifu" : "%wa en el canal de nekotina",
    "jalas" : "me la jalo cada que...",
    "moisi" : "el espanta chicas :miedo:",
    "moyai" : ":moyai:",
    "hola amigos" : ":cockroach:",
    "Examen forte" : "sigue en construcción pero ya saldrá... creo",
    "muerte" : "MUERTE",
    "python" : "ta mejor c#",
    "piña" : "piña jumpscare :susto:",
    "c#" : "besto lenguaje",
    "java" : "c# version 2",
    "javascript" : "java pero script",
    "xd" : "Sabías que vaporeon...",
    "piedra" : "todo piedra el que lo dijo",
    "terraria" : "calamity mod",
    "cheetoland" : "borrable",
    "calamity" : "besto mod",
    "cabrón" : "perreo hijoeputa",
    "gay" : "usted es bien joto me parece",
    "amogus" : "sus",
    "amogos" : "SSSUUSS",
    "geometry" : "ando medio inactivo en ese juego",
    "roblox" : "BALLER",
    "pizza" : "PIZZA DE PIÑA BESTO",
    "raid" : "espero no raidees el server",
    "culon" : "culon usted",
    "lenny" : "ese es bien feo",
    "cabra" : "todo cabra ese wn",
    "pelo" : "cabello",
    "jorge" : "el styles",
    "wahwah" : "el wawas",
    "dominic" : "soy yo",
    "dominicord" : "quien será xd",
    "exbor" : "JUAN PANCH MAN",
    "mech" : "todo piña",
    "alpako" : "todo pacas",
    "nilson" : "mantecas", 
    "luis" : "guis0",
    "ignorado" : "feo",
    "brosix" : "potaxio",
    "catmaster" : "gato maestro",
    "flaffy" : "flafffffffy",
    "wea" : "que wea",
    "ph4nther" : "diganle que pase rated",
    "mrc" : "si ven a mrc haciendo directo diganle que mirame jugar geometry dash en omlet arcade",
    "mr.c" : "si ven a mrc haciendo directo diganle que mirame jugar geometry dash en omlet arcade",
    "ruish" : "que se pase hollow knight otra vez",
    "danix" : "kriper amarillo",
    "dani" : "saca rpg dash",
    "cubezero" : "pariente lejano",
    "pendejo" : "pendejo tu vieja",
    "cuantos animes": "como 250",
    "cuántos animes": "como 250",
    "genshin" : "donde",
    "Vaporeon": "ya no lo voy a decir...",
    "es de raideo" : "No soy de raideo",
    "GD Catch" : "no me hables de ese nivel por ahora",
    "mejor" : "lo primero que dijiste",
    "fuerte" : "YO SOY EL MÁS FUERTE Y EL QUE LO NIEGUE ES TERRIBLE ENVIDIOSO",
    "descargo" : "descargate nekopara, besto juego",
    "robot" : "me da miedo que digas robot",
    "bot" : "soy un cubo",
    "anthomy" : "el Más cAgado del server",
    "miedo" : "no se asuste que me das miedo",
    "mierda" : "no me insultes CARAJO",
    "Turbio" : "turbio usted",
    "lo golpea" : "lo mata*",
    "jij" : "te ries...",
    "hola" : "Hola!",
    "verga" : "usted vale verga, yono",
    "?" : "nose",
    "saludo" : "hoal",
    "saludar" : "saludos",
    "holi": "Como que holi!",
    "HORRIBLE": "ME PARECE O ME ESTÁ INSULTADO",
    "HORRIBLES": "ME PARECE O ME ESTÁ INSULTADO???",
    "caca" : "bien feo",
    "JUGAh" : "NO QUIERO",
    "AUAJGH" : "no quiero jugah...",
    "odias" : "No",
    "odio" : ":(",
    "jaj" : "NO TE RIAS COMO PENDEJO",
  }

module.exports = {
    name: "di",
    descripcion: "Te responde según la palabra que coloques, si no colocas nada MUERTE",
    async execute(client, message, argumentos, discord){
        let texto = "";
        for (const i of argumentos) { texto += i.trim().toLowerCase() + " ";}
        for (const key in listaPiedra) {
            if(texto.includes(key.toLowerCase().trim())){
                message.reply(listaPiedra[key]);
                return;
            }
        }
        message.reply("disculpa, no tengo como responder a eso, quizás en un futuro");
    }
}